# Generated by Django 4.1.1 on 2022-09-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_api', '0002_event_topic_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='event_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.URLField(blank=True),
        ),
    ]
