# Generated by Django 4.1.1 on 2022-09-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower_api', '0004_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='event_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
