# Generated by Django 4.1.1 on 2022-09-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_api', '0005_alter_material_event_link_alter_material_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='title',
            new_name='topic',
        ),
    ]
