# Generated by Django 4.1.1 on 2022-09-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_api', '0007_remove_material_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='tower_api.topic'),
        ),
    ]
