# Generated by Django 4.1.1 on 2022-09-24 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_api', '0009_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='tower_api.course'),
        ),
        migrations.CreateModel(
            name='Clss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clss', models.CharField(max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clss', to='tower_api.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clss', to='tower_api.period')),
            ],
        ),
    ]
