# Generated by Django 4.1.1 on 2022-09-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_api', '0010_alter_period_course_clss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tower_api.clss')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tower_api.event')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tower_api.material')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tower_api.teacher')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tower_api.topic')),
            ],
        ),
    ]
