# Generated by Django 4.1.1 on 2022-09-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_api', '0013_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PR', 'Present'), ('AB', 'Absent'), ('SK', 'Sick'), ('LV', 'Leave')], default='PR', max_length=2)),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='tower_api.clss')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='tower_api.lesson')),
                ('student', models.ManyToManyField(to='tower_api.student')),
            ],
        ),
    ]
