# Generated by Django 4.1.1 on 2022-09-25 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower_api', '0014_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='tower_api.teacher')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='tower_api.teacher')),
            ],
        ),
    ]
