# Generated by Django 4.1.1 on 2022-09-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tower_api', '0015_alter_teacher_salary_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='salary',
        ),
    ]
